Allow disabling `cc`'s ability to run commands via the `CC_FORCE_DISABLE` environment variable
rust-lang/cc-rs pull request #1226
Opened 2024-10-02 23:08 UTC by thomcc

This came up in RustConf as a desire from users/maintainers of 3rd-party build systems, such as Buck2, Bazel, and their ilk.

The idea is that they should be in full control over building all native dependencies, and currently it's (apparently) very annoying and time-consuming to ensure that no `build.rs` is compiling/assembling/linking/etc native libraries on it's own. By setting this flag, they can get an error on any crate that attempts this.

In terms of the implementation, this was more invasive than I'd like, and I'm open to suggestions about alternative ways of doing this. I failed to locate a single choke-point where returning a `Result::Err` would sufficiently neuter our functionality.

I think the approach I've taken is awkward, and would be borderline-unmaintainable were it not for `clippy::disallowed_methods`. That said, we do have access to that clippy lint, which I think pushes this over the edge.

2024-10-02 23:12 UTC, thomcc commented on clippy.toml
> +    { path = "cc::tool::Tool::to_command", reason = "Bypasses `is_disabled()` check. Use try_to_command() instead." },
This is just for internals, obviously users can continue to use `Tool::to_command` as much as they want.

2024-10-02 23:12 UTC, thomcc commented on src/tool.rs
> +                        zig_cc: is_zig_cc(&path, cargo_output).unwrap_or(false),
`unwrap_or(false)` here is a bit janky. I don't think it makes much of a difference what we report when `cc` is disabled, though.

2024-10-02 23:12 UTC, thomcc commented on src/lib.rs
> +pub(crate) fn is_disabled() -> bool {
It's unfortunate that this is toplevel and not on `Build`, but changing everywhere that produces `Command`s to take a `&Build` was far too invasive a change. This already is pushing it.

2024-10-03 07:44 UTC, NobodyXu requested changes
How about adding checks to `Build::compile_objects`?

It is the function responsible for doing the actual compilation, all other functions compile/try_compile/compile_intermediates/try_compile_intermediates all delegate to it.

2024-10-03 08:01 UTC, ChrisDenton commented
Tbh this does seem a more general problem with the architecture of Cargo's build scripts rather than cc per se. But if using cc as a proxy helps as a mitigation then I'm not against it.

2024-11-15 08:59 UTC, closed without merging