Support new NTO QNX targets
rust-lang/cc-rs pull request #1312
Opened 2024-12-03 12:31 UTC by flba-eb

This change:
- Adds support for two new targets
- Adds support for a new target_env value
- Gives users a bit more information where an error message comes from (e.g. if target is unknown)

This depends on rust-lang/rust/pull/133631

CC: @jonathanpallant @japaric @gh-tr @AkhilTThomas

2024-12-03 13:38 UTC, madsmtm commented
Thanks for the PR!

The `generated.rs` shouldn't be updated manually, it will be updated by a CI job within a week of the Rust PR merging.

Also, please add the better error message in a separate PR.

---

I think this is the first time that a Rust target is added since https://github.com/rust-lang/cc-rs/pull/1225, I'd like to know what you think we can do better (apart from improving the error message) to make that work smoother in the future?

2024-12-04 07:16 UTC, flba-eb commented
> Thanks for the PR!
> 
> The `generated.rs` shouldn't be updated manually, it will be updated by a CI job the next Friday after the Rust PR merges.
> 
> I think this is the first time that a Rust target is added since #1225, I'd like to know what you think we can do better (apart from improving the error message) to make such work smoother in the future?

Thanks for the feedback, I've reverted the changes of `generated.rs`.

Something that would have helped me (and I think @thejpster as well) is:
- A note in https://rustc-dev-guide.rust-lang.org/building/new-target.html about this issue. It does mention some required changes in e.g. `Cargo.toml` to allow targets not yet supported by nightly Rust, but nothing about the cc crate.
- A more clear error message of the cc crate. This PR tries to improve it a bit (so that the user at least knows where the error message is coming from), but e.g. a link to some additional documentation (like the dev guide of previous bullet point) could be even better.

2024-12-05 08:32 UTC, NobodyXu commented
> The generated.rs shouldn't be updated manually, it will be updated by a CI job the next Friday after the Rust PR merges.

You can modify and run `cargo run` inside the dev-tools/gen-target-info https://github.com/rust-lang/cc-rs/tree/main/dev-tools/gen-target-info

It will generate this src/target/generated

2025-02-08 09:19 UTC, NobodyXu requested changes
Thanks, LGTM!

cc @madsmtm can you double check this please ?

2025-02-08 09:19 UTC, NobodyXu approved these changes

2025-02-08 14:35 UTC, madsmtm approved these changes

2025-02-08 14:41 UTC, merged