Fix compiler family detection issue with clang-cl on macOS
rust-lang/cc-rs pull request #1328
Opened 2024-12-22 13:35 UTC by NobodyXu

Fixed #1327

2024-12-22 14:00 UTC, NobodyXu commented
I can't know for sure if the compiler is clang-cl, so can't apply the workaround reliably.

Alternatively, we could combine `cfg(macos)` with accept cl flags check.

if both are true then it's likely clang-cl on macOS, which needs workaroud.

2025-01-01 18:06 UTC, madsmtm requested changes
It is not clear to me why we even support `clang-cl` on macOS and Linux? `cl.exe` is not something you'd run on those platforms, so why would you ever run `clang-cl`?

> `cfg(macos)`

That's a bad idea IMO, since this problem is also present on Linux and Windows hosts, just less prominently since their root paths usually start with a lowercase letter (on Linux), or prefixed with the drive letter (on Windows), but that's not a requirement!

---

Actually, the `--` separator seems to be supported by normal Clang too, so why don't we just do this workaround everywhere?

This would also avoid issues if the user did e.g. `.file("-l")`.

2025-01-02 03:02 UTC, NobodyXu commented
> It is not clear to me why we even support `clang-cl` on macOS and Linux? `cl.exe` is not something you'd run on those platforms, so why would you ever run `clang-cl`?

Based on the original issue, I believe they are using cargo-xwin to cross compile to msvc windows from a unix environment.

> Actually, the `--` separator seems to be supported by normal Clang too, so why don't we just do this workaround everywhere?

Does gcc and other compiler support it?

If they mostly do, we can add `--` to compiler detection.

> This would also avoid issues if the user did e.g. `.file("-l")`.

Good idea

2025-01-02 04:26 UTC, madsmtm commented
> Does gcc and other compiler support it?

```console
$ touch a.c
$ gcc -- a.c
gcc: error: unrecognized command-line option '--'
```

Doesn't seem like it?

2025-01-06 15:19 UTC, madsmtm commented on src/tool.rs
> +            let accepts_cl_style_flags =
Hmm, I'm wondering, can't we do this check _first_, and then use that to figure out whether to do `--` or not based on that?

Or, does `cl.exe` not support `--` either?

2025-01-06 15:19 UTC, madsmtm commented on src/tool.rs
> +            if stdout.contains("-Wslash-u-filename") {
This... Seems brittle :/.

Not that I have a better solution (yet).

2025-01-06 15:57 UTC, madsmtm commented on src/tool.rs
> +            let accepts_cl_style_flags =
Ah, yeah, it doesn't.

2025-01-06 16:14 UTC, madsmtm commented on src/tool.rs
>                  Command::new(path).arg("-E").arg(tmp.path()),
Actually, I wonder, why don't we just detect the compiler by running `$path -v`?

Output `clang -v` on macOS:
```console
Apple clang version 16.0.0 (clang-1600.0.26.6)
Target: arm64-apple-darwin23.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Output `gcc -v` on Ubuntu:
```console
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/aarch64-linux-gnu/11/lto-wrapper
Target: aarch64-linux-gnu
Configured with: [...]
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
```

Output `cl.exe -v` on Windows (taking advantage of `cl` always outputting version information):
```console
Microsoft (R) C/C++ Optimizing Compiler Version 19.42.34435 for x86
Copyright (C) Microsoft Coporation.  All rights reserved

cl : Command line warning D9002 : ignoring unknown option '-v'
cl : Command line error D8003 : missing source filename

```

2025-01-06 16:18 UTC, madsmtm commented on src/tool.rs
>                  Command::new(path).arg("-E").arg(tmp.path()),
And then `$path -?` to differentiate `clang-cl` from `clang`.

2025-01-07 09:18 UTC, NobodyXu commented on src/tool.rs
>                  Command::new(path).arg("-E").arg(tmp.path()),
I think this is what we are previously doing, but get removed due to not reliable enough.

2025-01-07 09:18 UTC, NobodyXu commented on src/tool.rs
> +            if stdout.contains("-Wslash-u-filename") {
I don't like it either, but I really can't think of an alternative solution that is better

2025-01-07 17:27 UTC, madsmtm commented on src/tool.rs
>                  Command::new(path).arg("-E").arg(tmp.path()),
Hmm, I suspected so. Found https://github.com/rust-lang/cc-rs/pull/1000.

2025-01-07 17:28 UTC, madsmtm commented on src/tool.rs
> +            if stdout.contains("-Wslash-u-filename") {
What does CMake do?

2025-01-08 09:23 UTC, NobodyXu commented on src/tool.rs
> +            if stdout.contains("-Wslash-u-filename") {
Not sure , I didn't check about cmake.

I did remember the `-?` solution is copied from it, so perhaps it uses that as a hint?

2025-01-08 21:41 UTC, madsmtm approved these changes
I don't feel I know enough to really gauge whether this is the right approach or not, so I'll leave that up to you.

I don't think GitHub allows me to make a neutral review after having requested changes, so just so that won't block you, I've approved it.

2025-01-08 23:13 UTC, NobodyXu commented
Thanks, let me merge it and try shipping it, if it doesn't work we have to revert

2025-01-08 23:13 UTC, merged

2025-01-11 11:20 UTC, messense commented
Unfortunately it seems to broke `cargo-zigbuild` badly: https://github.com/rust-cross/cargo-zigbuild/actions/runs/12723439506/job/35468553100

> error occurred in cc-rs: Command LC_ALL="C" "/home/runner/.cache/cargo-zigbuild/0.19.7/zigcc-aarch64-unknown-linux-gnu-6363.sh" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "--target=aarch64-unknown-linux-gnu" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-fvisibility=hidden" "-DZSTD_LIB_DEPRECATED=0" "-DXXH_PRIVATE_API=" "-DZSTDLIB_VISIBILITY=" "-DZDICTLIB_VISIBILITY=" "-DZSTDERRORLIB_VISIBILITY=" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/home/runner/work/cargo-zigbuild/cargo-zigbuild/tests/zstd-rs/target/aarch64-unknown-linux-gnu/debug/build/zstd-sys-c42cdd11ab2b8d1c/out/7faed3f8272f2313-huf_decompress_amd64.o" "-c" "--" "zstd/lib/decompress/huf_decompress_amd64.S" with args zigcc-aarch64-unknown-linux-gnu-6363.sh did not execute successfully (status code exit status: 1).

2025-01-11 11:23 UTC, messense commented
And it does not seem to resolve the clang-cl issue either:

> warning: libz-ng-sys@1.1.16: Compiler family detection failed due to error: ToolExecError: Command "clang-cl" "-E" "/Users/messense/Projects/uv/target/aarch64-pc-windows-msvc/debug/build/libz-ng-sys-e348506bb081d40e/out/442624705732975273detect_compiler_family.c" with args clang-cl did not execute successfully (status code exit status: 1).

2025-01-11 14:19 UTC, tokatoka commented
I think this will break if people uses `cc` with their own compiler wrappers 

For our case, we use a compiler wrapper based on clang and in our wrapper we didn't handle argument `--` .
This fix automatically adds "--" automatically, and we had to handle it else it broke.

2025-01-11 14:31 UTC, NobodyXu commented
@messense @tokatoka I've opened #1359, can you try it out please?

2025-01-11 16:05 UTC, tbetcke commented
@NobodyXu I have the same issue with `mpicc` as compiler wrapper (e.g. used by [rsmpi](https://github.com/rsmpi/rsmpi). Version 1.2.7 of `cc-rs` works fine. Version `1.2.8` fails with the `--` issue.