Add option to emit `rerun-if-env-changed` metadata
rust-lang/cc-rs pull request #701
Opened 2022-07-19 04:48 UTC by nathaniel-daniel

Partially fixes #230 by emitting directives for environment variables. Looking at #443, it seems uncontroversial to add an option to emit this metadata for environment variables. 

This PR adds an option called `emit_rerun_if_env_changed` to control this behavior, defaulted to false. I added a check in `getenv` to print the metadata if this flag is true. Since I use the `print` function, `cargo_metadata` must also be true for this flag to have any effect.

2022-10-26 03:41 UTC, thomcc requested changes
This is mostly good, but I'd like to avoid emitting this for the same var multiple times.

2022-10-26 03:41 UTC, thomcc commented on src/lib.rs
> +        if self.emit_rerun_if_env_changed {
We only need to do this if the var was not cached, so this ideally would be only in the branch that fails to read from the cache.

2022-10-29 04:58 UTC, thomcc approved these changes
This looks better. In the future it would be nice to avoid doing this for vars cargo sets on its own, but I don't know how much that matters.

2022-10-29 04:59 UTC, merged

2022-10-29 07:22 UTC, thomcc commented
Thinking more, I'm really unsure why we wouldn't default this to true.

2022-10-30 05:20 UTC, nathaniel-daniel commented
Thanks for the merge/fixes.

>This looks better. In the future it would be nice to avoid doing this for vars cargo sets on its own, but I don't know how much that matters.

I figured it didn't matter too much, and wasn't sure how much overhead checking a list would be. 

> Thinking more, I'm really unsure why we wouldn't default this to true.

I was going off of https://github.com/rust-lang/cc-rs/pull/443#issuecomment-535144089 for this PR. I guess its conceivable that a build script may not support being rerun, so emitting rerun metadata might break those since I think cargo metadata is emitted by default. However, I couldn't find the exact rationale behind defaulting to false. 

I wanted to create an uncontroversial PR to improve the situation around rerunning, since progress there seemed to have stalled for half a decade and I run into this issue a lot. 

Also, is #230 considered fixed by this? Is there nothing that can be done for files aside from expecting the user to emit metadata themselves?