move Windows code into a module
rust-lang/cc-rs pull request #924
Opened 2024-01-29 01:12 UTC by Be-ing

2024-01-29 01:35 UTC, Be-ing commented on src/lib.rs
> +pub use windows::find_tools as windows_registry;
Maybe make this `#[doc(hidden)]`?

2024-01-30 00:38 UTC, NobodyXu requested changes
Thanks, overall it LGTM but has two minor suggestions.

Also, can you please run gen-windows-sys-binding locally to make sure it works with the changed location?

2024-01-30 00:38 UTC, NobodyXu commented on src/lib.rs
> +        let cl_exe = windows::find_tools::find_tool(target, "cl.exe");
there's no need to change this line:

```suggestion
        let cl_exe = windows_registry::find_tool(target, "cl.exe");
```

2024-01-30 00:38 UTC, NobodyXu commented on src/lib.rs
> +                        let mut cmd = match windows::find_tools::find(&target, "lib.exe") {
Same here:

```suggestion
                        let mut cmd = match windows_registry::tools::find(&target, "lib.exe") {
```

2024-01-30 03:51 UTC, Be-ing commented on src/lib.rs
> +        let cl_exe = windows::find_tools::find_tool(target, "cl.exe");
done

2024-01-30 03:51 UTC, Be-ing commented on src/lib.rs
> +                        let mut cmd = match windows::find_tools::find(&target, "lib.exe") {
done

2024-01-30 03:52 UTC, Be-ing commented
> Also, can you please run gen-windows-sys-binding locally to make sure it works with the changed location?

Ah yeah, it needed a little adjustment since moving gen-windows-sys-binding to the dev-tools directory in #927. Now it works regardless of how you run gen-windows-sys-binding.

2024-01-30 03:55 UTC, Be-ing commented
This is easier to navigate now:

```
cc-rs on  windows_mod [$] is 📦 v1.0.84 via 🦀 v1.75.0 on ☁  (auto) 
❯ tree
.
├── Cargo.toml
├── dev-tools
│   ├── cc-test
│   │   ├── build.rs
│   │   ├── Cargo.toml
│   │   ├── src
│   │   │   ├── aarch64.asm
│   │   │   ├── aarch64.S
│   │   │   ├── armv7.S
│   │   │   ├── bar1.c
│   │   │   ├── bar2.c
│   │   │   ├── baz.cpp
│   │   │   ├── compile_error.c
│   │   │   ├── cuda.cu
│   │   │   ├── dummy.c
│   │   │   ├── expand.c
│   │   │   ├── foo.c
│   │   │   ├── i686.asm
│   │   │   ├── i686.S
│   │   │   ├── include
│   │   │   │   └── foo.h
│   │   │   ├── lib.rs
│   │   │   ├── msvc.c
│   │   │   ├── NMakefile
│   │   │   ├── opt_linkage.c
│   │   │   ├── riscv64gc.S
│   │   │   ├── windows.c
│   │   │   ├── x86_64.asm
│   │   │   └── x86_64.S
│   │   └── tests
│   │       ├── all.rs
│   │       └── output.rs
│   └── gen-windows-sys-binding
│       ├── Cargo.toml
│       ├── src
│       │   └── main.rs
│       └── windows_sys.list
├── LICENSE-APACHE
├── LICENSE-MIT
├── README.md
├── src
│   ├── bin
│   │   └── gcc-shim.rs
│   ├── command_helpers.rs
│   ├── lib.rs
│   ├── os_pipe
│   │   ├── mod.rs
│   │   ├── unix.rs
│   │   └── windows.rs
│   ├── parallel
│   │   ├── async_executor.rs
│   │   ├── job_token
│   │   │   ├── mod.rs
│   │   │   ├── unix.rs
│   │   │   └── windows.rs
│   │   └── mod.rs
│   ├── tool.rs
│   └── windows
│       ├── com.rs
│       ├── find_tools.rs
│       ├── mod.rs
│       ├── registry.rs
│       ├── setup_config.rs
│       ├── vs_instances.rs
│       ├── winapi.rs
│       └── windows_sys.rs
└── tests
    ├── cc_env.rs
    ├── cflags.rs
    ├── cxxflags.rs
    ├── support
    │   └── mod.rs
    └── test.rs

16 directories, 58 files
```

2024-01-30 06:40 UTC, NobodyXu approved these changes
Thanks!

2024-01-30 06:41 UTC, merged