add Build::apple_deployment_target function
rust-lang/cc-rs pull request #938
Opened 2024-01-30 11:17 UTC by Be-ing

flag_if_supported doesn't work for this because try_get_compiler adds the Apple deployment target argument before flags_supported is processed, so users can only append a second -mmacosx-version-min flag via flag_if_supported. To work around this, add a function specifically for this purpose.

2024-01-30 13:11 UTC, NobodyXu requested changes

2024-01-30 13:11 UTC, NobodyXu commented on src/lib.rs
> +    fn get_apple_deployment_target(
Can we change the return type to `Cow<'_, str>` to avoid cloning `str`?

2024-01-30 13:12 UTC, NobodyXu commented
This seems like related to #902

2024-02-04 21:13 UTC, NobodyXu commented
cc @Be-ing if you don't mind it, I can update the PR for you.

2024-02-04 22:05 UTC, Be-ing commented
I did some more testing, and the existing `flag_if_supported` API does work. I am not sure exactly how the CLI arguments are handled by clang. When `-mmacosx-version-min` is passed twice (first time automatically by cc, second time by user-specified `flag_if_supported`), it seems to either prefer the second argument or the higher specified version. It might still be a good idea to add this API though because that behavior of clang is not documented and I don't know if it can be relied on long term. Thoughts?

2024-02-04 22:54 UTC, NobodyXu commented
IMO it's better to add this API, not just due to the order of cmdline arg, but cc-rs seems to have different behavior based on apple deployment target version and build target.

2024-02-05 02:18 UTC, Be-ing commented
> cc-rs seems to have different behavior based on apple deployment target version and build target

Yes, but that can be addressed using the existing `flag_if_supported` API, so should we add a new API?

2024-02-05 02:57 UTC, NobodyXu commented
If that can be reliably solved by `flag_if_supported()` on all compilers, then it is indeed unnecessary.

But I'm not sure if it would work on gcc or msvc.

2024-02-05 04:54 UTC, BlackHoleFox commented on src/lib.rs
> +            AppleOs::WatchOs => deployment_from_env("_DEPLOYMENT_TARGET")
This looks like an error maybe?

2024-02-05 05:03 UTC, Be-ing commented on src/lib.rs
> +            AppleOs::WatchOs => deployment_from_env("_DEPLOYMENT_TARGET")
whoops, yeah that was an accident

2024-02-12 13:24 UTC, closed without merging

2024-02-12 20:46 UTC, BlackHoleFox commented
@Be-ing On the contrary I think this should still be added. `MACOSX_DEPLOYMENT_TARGET` only works if you either set it outside of the process in a Makefile, cargo env config, etc or use `std::env::set_var` at runtime inside `build.rs`. 

That last option is the only programmatic way to do it and manipulating the process' environment variables is an uh, [dicey area](github.com/rust-lang/rust/issues/90308). Having a proper library API to control this for each target would be nice imo.

2024-02-13 01:47 UTC, Be-ing commented
Now that the old behavior of defaulting to the SDK's default deployment target has been restored, what is the need for this API? The default is a recent deployment target, so old code builds fine. A crate specifying a lower minimum than the default wouldn't really change anything.

2024-02-14 03:23 UTC, BlackHoleFox commented
> A crate specifying a lower minimum than the default wouldn't really change anything.

What do you mean?

2024-02-14 07:18 UTC, Be-ing commented
If a crate specifies a lower deployment target than the default, it's effectively superfluous because it would have built anyway. Only if *every* crate in the dependency graph that uses cc specifies the same lower deployment target will the resulting binary actually be usable on the lower deployment target. That's best achieved via the environment variable because that effects every crate that uses cc.

2024-02-14 07:31 UTC, BlackHoleFox commented
Seems like a reasonable take, the well-stated counter-argument is appreciated :)