fix targets with zig toolchain
rust-lang/cc-rs pull request #986
Opened 2024-03-02 22:57 UTC by QuentinPerez

When you use bazel + zig to cross compile a rust codebase, you got an 'invalid target error'
To fix the issue, a check has been added to know if it's a zig toolchain, not sure it's the right way to do it. 
Feel free to take over the PR.

2024-03-02 23:29 UTC, NobodyXu requested changes
It would be great if you could setup CI for testing zig-cc, to verify it indeed works as intended.

2024-03-03 18:06 UTC, QuentinPerez commented
> It would be great if you could setup CI for testing zig-cc, to verify it indeed works as intended.

I tried it, but I am not sure how to achieve it correctly. Do you have any ideas or guidance on how I could do it?

2024-03-03 22:36 UTC, NobodyXu commented
Simply install `pip3 install zig` in job test of `.github/workflows/main.yml`.

You would also need to add a `tests/zig-test.rs` and write all the testing for `zig-cc` in it.

2024-03-08 07:58 UTC, NobodyXu requested changes

2024-03-08 07:58 UTC, NobodyXu commented on src/tool.rs
> +                    is_zig: stdout.contains("ziglang"),
Just note that I've updated how compiler family detection work in #1000

Recommend you to wait for it to merge and then rebase against it.

2024-03-19 07:46 UTC, NobodyXu commented
@QuentinPerez #1000 has been merged, can you rebase against main please?

2024-03-22 11:35 UTC, NobodyXu requested changes

2024-03-22 11:35 UTC, NobodyXu commented on src/lib.rs
> +
Could do a

```suggestion
            let target = target.as_ref();

```

To avoid changing every if that uses target

2024-03-22 21:40 UTC, NobodyXu reviewed
Thanks, the code itself LGTM, can you add a test for zig-cc in CI?

You can just run cargo-test, while setting environment variable CC to zig-cc

2024-03-29 00:58 UTC, NobodyXu commented
Discussed this with @thomcc on zulip, he mentioned that the zig-cc target triple might be changed in the later version of zig-cc.

We are afraid that after merging this PR, zig-cc might change its target triple and break this, causing more code to require to support both newer version and older version.

We decided to hold off adding more workarounds for zig-cc until it reaches 1.0, when its target triple and cmdline args are stable.

2024-03-29 00:58 UTC, closed without merging